// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdtblxpazmdfunvvxahy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdGJseHBhem1kZnVudnZ4YWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MzI5NTcsImV4cCI6MjA4NjIwODk1N30.RB9IV_FUpNtYbEIQMDX3txmzhm0s6_GB_O7FagMCNZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});