// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktqszorayutpmxsdwcsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cXN6b3JheXV0cG14c2R3Y3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMDQ1NTksImV4cCI6MjA4NTU4MDU1OX0.ftE2bVD7u0WGsD_XgdY8CdeQLyHaEfZncbIdGDo6kjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});